# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'addEditCoffeeForm.ui'
#
# Created by: PyQt5 UI code generator 5.15.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(475, 510)
        self.label = QtWidgets.QLabel(Form)
        self.label.setGeometry(QtCore.QRect(190, 40, 67, 19))
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(Form)
        self.label_2.setGeometry(QtCore.QRect(160, 90, 131, 19))
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(Form)
        self.label_3.setGeometry(QtCore.QRect(190, 140, 67, 19))
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(Form)
        self.label_4.setGeometry(QtCore.QRect(150, 190, 151, 19))
        self.label_4.setObjectName("label_4")
        self.label_5 = QtWidgets.QLabel(Form)
        self.label_5.setGeometry(QtCore.QRect(200, 280, 67, 19))
        self.label_5.setObjectName("label_5")
        self.label_6 = QtWidgets.QLabel(Form)
        self.label_6.setGeometry(QtCore.QRect(190, 330, 67, 19))
        self.label_6.setObjectName("label_6")
        self.Enter = QtWidgets.QPushButton(Form)
        self.Enter.setGeometry(QtCore.QRect(40, 450, 100, 31))
        self.Enter.setObjectName("Enter")
        self.name = QtWidgets.QLineEdit(Form)
        self.name.setGeometry(QtCore.QRect(160, 60, 111, 21))
        self.name.setObjectName("name")
        self.level = QtWidgets.QLineEdit(Form)
        self.level.setGeometry(QtCore.QRect(160, 110, 111, 21))
        self.level.setObjectName("level")
        self.grinding = QtWidgets.QLineEdit(Form)
        self.grinding.setGeometry(QtCore.QRect(160, 160, 111, 21))
        self.grinding.setObjectName("grinding")
        self.descr = QtWidgets.QLineEdit(Form)
        self.descr.setGeometry(QtCore.QRect(20, 210, 431, 61))
        self.descr.setObjectName("descr")
        self.cost = QtWidgets.QLineEdit(Form)
        self.cost.setGeometry(QtCore.QRect(160, 300, 111, 21))
        self.cost.setObjectName("cost")
        self.volume = QtWidgets.QLineEdit(Form)
        self.volume.setGeometry(QtCore.QRect(160, 360, 111, 21))
        self.volume.setObjectName("volume")

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.label.setText(_translate("Form", "name"))
        self.label_2.setText(_translate("Form", "level of roasting"))
        self.label_3.setText(_translate("Form", "grinding"))
        self.label_4.setText(_translate("Form", "description of taste"))
        self.label_5.setText(_translate("Form", "cost"))
        self.label_6.setText(_translate("Form", "volume"))
        self.Enter.setText(_translate("Form", "Enter"))
