# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'main.ui'
#
# Created by: PyQt5 UI code generator 5.15.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_widget(object):
    def setupUi(self, widget):
        widget.setObjectName("widget")
        widget.resize(554, 547)
        self.label = QtWidgets.QLabel(widget)
        self.label.setGeometry(QtCore.QRect(280, 0, 281, 511))
        self.label.setText("")
        self.label.setObjectName("label")
        self.tableWidget = QtWidgets.QTableWidget(widget)
        self.tableWidget.setGeometry(QtCore.QRect(0, 0, 271, 511))
        self.tableWidget.setObjectName("tableWidget")
        self.tableWidget.setColumnCount(0)
        self.tableWidget.setRowCount(0)
        self.tableWidget.horizontalHeader().setDefaultSectionSize(150)
        self.add = QtWidgets.QPushButton(widget)
        self.add.setGeometry(QtCore.QRect(40, 510, 171, 31))
        self.add.setObjectName("add")
        self.change = QtWidgets.QPushButton(widget)
        self.change.setGeometry(QtCore.QRect(330, 510, 171, 31))
        self.change.setObjectName("change")

        self.retranslateUi(widget)
        QtCore.QMetaObject.connectSlotsByName(widget)

    def retranslateUi(self, widget):
        _translate = QtCore.QCoreApplication.translate
        widget.setWindowTitle(_translate("widget", "Эспрессо"))
        self.add.setText(_translate("widget", "add"))
        self.change.setText(_translate("widget", "change"))
